export const triviaAnswer = [['¿Qué significa HTML?',
    'Hyperlink Markup Language',
    'Hypertext Markup Language',
    'High Transfer Markup Language',
    'Hypertext Machine Language',
    'B'],
['¿Cuál de estos NO es un lenguaje de programación?',
    'Python',
    'JavaScript',
    'MySQL',
    'HTML',
    'D']

    , ['¿Qué hace el método push() en JavaScript?',
    'Añade un elemento al inicio de un array',
    'Elimina el último elemento de un array',
    'Añade un elemento al final de un array',
    'Crea un nuevo array',
    'C'],
['¿Qué significa CSS?',
    'Cascading Style Sheets',
    'Centralized Style System',
    'Computer Styling System',
    'Color Styling Sheets',
    'A'],
['¿Qué devuelve typeof null en JavaScript?',
    'null',
    'object',
    'undefined',
    'boolean',
    'B']

    , ['¿Cuál es el propósito principal de una base de datos?',
    'Dibujar gráficos',
    'Almacenar y organizar datos',
    'Crear aplicaciones',
    'Generar archivos PDF',
    'B'],
['¿Qué símbolo se usa para denotar comentarios en CSS?',
    '// comentario',
    '/* comentario */',
    '# comentario',
    '-- comentario',
    'B'],
['¿Qué framework de JavaScript es desarrollado por Meta (antes Facebook)?',
    'Angular',
    'Vue',
    'React',
    'Ember',
    'C'],
['¿Qué función de JavaScript se utiliza para convertir un JSON en un objeto?',
    'JSON.parse()',
    'JSON.stringify()',
    'JSON.convert()',
    'JSON.toObject()',
    'A'],
['¿Qué es una promesa (Promise) en JavaScript?',
    'Una función que siempre se ejecuta inmediatamente',
    'Un método para manejar operaciones asíncronas',
    'Una declaración que asegura el funcionamiento del código',
    'Un tipo de variable global',
    'B'],
['¿Qué es Git?',
    'Un sistema de control de versiones',
    'Un lenguaje de programación',
    'Un servidor web',
    'Una librería de Node.js',
    'A'],
['¿Cuál es la diferencia entre let y const en JavaScript?',
    'let es una variable global y const es local',
    'const no puede ser reasignado, pero let sí',
    'let define constantes y const variables',
    'No hay diferencia, son intercambiables',
    'B'],
['¿Qué etiqueta de HTML se usa para incluir un archivo de JavaScript?',
    ' < script >',
    ' < js >',
    ' < link >',
    ' < style >',
    'A'],
['¿Cuál es el propósito del useEffect en React?',
    'Crear un nuevo componente',
    'Manejar efectos secundarios en componentes funcionales',
    'Renderizar listas',
    'Actualizar el estado global',
    'B'],
['¿Qué resultado da 2 + "2" en JavaScript?',
    '22',
    '4',
    'NaN',
    'Error',
    'A'],
['¿Qué significa NaN en JavaScript?',
    'Not a Number',
    'No access Number',
    'Null and None',
    'Number as Null',
    'A'],
['¿Cuál es el protocolo más usado para transferir datos en aplicaciones web?',
    'HTTP',
    'FTP',
    'SMTP',
    'SSH',
    'A'],
['¿Qué operador lógico representa OR en JavaScript?',
    ' &&',
    ' ||',
    '!',
    ' ==',
    'B'],
['¿Qué comando de Git se usa para clonar un repositorio?',
    'git copy',
    'git download',
    'git clone',
    'git fork',
    'C'], ['¿Qué herramienta sirve para manejar dependencias en un proyecto de Node.js?',
    'npm',
    'pip',
    'Composer',
    'Maven',
    'A'],
['¿Qué propiedad de CSS se utiliza para cambiar el color del fondo?',
    'background - color',
    'color',
    'background',
    'border - color',
    'A'],
['¿Qué significa la consola console.log() en JavaScript ?',
    'Muestra un error en el navegador',
    'Imprime un mensaje en la consola',
    'Llama a una función del sistema',
    'Detiene la ejecución del código',
    'B'],
['¿Qué método se usa para detener un evento en JavaScript?',
    'stopPropagation()',
    'preventDefault()',
    'Ambos',
    'Ninguno',
    'C'],
['¿Cuál de los siguientes es un lenguaje de estilos?',
    'Ruby',
    'CSS',
    'PHP',
    'SQL',
    'B'],
['¿Cómo se declara un componente funcional en React?',
    'function MiComponente() { ... }',
    'const MiComponente = () => { ... }',
    'Ambos son válidos',
    'Ninguno es válido',
    'C'],
['¿Cuál es el servidor web más usado para proyectos de JavaScript?',
    'Apache',
    'Nginx',
    'Node.js',
    'IIS',
    'C'],
['¿Qué significa CRUD en desarrollo web?',
    'Create, Read, Update, Delete',
    'Compile, Run, Update, Deploy',
    'Create, Render, Update, Debug',
    'Create, Read, Upload, Download',
    'A'],
['¿Qué hace el método map() en JavaScript?',
    'Itera sobre un array y devuelve un nuevo array',
    'Elimina elementos de un array',
    'Filtra elementos de un array',
    'Encuentra un elemento en un array',
    'A'],
['¿Cuál es el propósito de this en JavaScript?',
    'Referirse al contexto global',
    'Referirse al contexto actual',
    'Crear una nueva variable',
    'Llamar a una función anónima',
    'B'],
['¿Qué significa "responsive design"?',
    'Diseñar sitios web que responden a eventos',
    'Crear diseños adaptativos para diferentes dispositivos',
    'Diseñar aplicaciones sin errores',
    'Crear diseños rápidos y minimalistas',
    'B'],
['¿Qué framework de CSS se usa principalmente para estilos predefinidos y flexibilidad?',
    'Tailwind CSS',
    'Flask',
    'Django',
    'Vue.js',
    'A'],
['¿Qué hace el hook useState en React?',
    'Administra el estado de los componentes',
    'Administra los efectos secundarios',
    'Controla el ciclo de vida del componente',
    'Renderiza el DOM directamente',
    'A'],
['¿Cómo se escribe un selector de clase en CSS?',
    'nombre-clase',
    '#nombre - clase',
    'nombre - clase',
    ': nombre - clase',
    'A'],
['¿Qué es un "callback" en programación?',
    'Una función que se pasa como argumento a otra función',
    'Una variable global utilizada en programación',
    'Un método exclusivo de APIs',
    'Un bucle dentro de una función',
    'A'],
['¿Qué librería se usa comúnmente con React para manejo de estados globales?',
    'Redux',
    'Lodash',
    'Bootstrap',
    'Express',
    'A'], ['¿Qué etiqueta de HTML se utiliza para crear un enlace?',
    ' < a >',
    ' < link >',
    ' < href >',
    ' < anchor >',
    'A'],
['¿Qué función se usa para convertir un string a un número entero en JavaScript?',
    'parseInt()',
    'Number()',
    'toInteger()',
    'parseNumber()',
    'A'],
['¿Qué atributo de HTML se usa para especificar un identificador único?',
    'class',
    'id',
    'name',
    'key',
    'B'],
['¿Qué significa JSX en React?',
    'JavaScript XML',
    'JavaScript Xperience',
    'JavaScript Extended',
    'JavaScript Execution',
    'A'],
['¿Qué unidad de medida en CSS es relativa al tamaño de la fuente?',
    'px',
    'em',
    'vh',
    ' %',
    'B'],
['¿Qué evento se utiliza para detectar cuando un usuario envía un formulario en JavaScript?',
    'onChange',
    'onInput',
    'onSubmit',
    'onClick',
    'C'],
['¿Qué comando en Git se usa para ver el historial de commits?',
    'git show',
    'git history',
    'git log',
    'git commits',
    'C'],
['¿Qué método de JavaScript convierte un array en un string?',
    'join()',
    'split()',
    'concat()',
    'toString()',
    'A'],
['¿Cuál es el valor inicial de this en el contexto global en un navegador?',
    'window',
    'document',
    'undefined',
    'null',
    'A'], ['¿Qué etiqueta de HTML se usa para incluir imágenes?',
    ' < img >',
    ' < picture >',
    ' < media >',
    ' < image >',
    'A'],
['¿Cuál es la salida de console.log(0, [0.1 + 0.2 === 0.3) en JavaScript?',
    'true',
    'false',
    'NaN',
    'undefined',
    'B'],
['¿Qué es un "component" en React?',
    'Una pieza reutilizable de interfaz de usuario',
    'Un método de renderizado del DOM',
    'Una extensión de CSS',
    'Un archivo JSON en el proyecto',
    'A'],
['¿Qué significa API?',
    'Application Programming Interface',
    'Automated Programming Integration',
    'Applied Program Instructions',
    'Abstract Program Interface',
    'A'],
['¿Qué método de JavaScript devuelve el índice de un elemento en un array?',
    'find()',
    'indexOf()',
    'filter()',
    'includes()',
    'B'],
['¿Qué framework de JavaScript es conocido por ser el más "opinionado"?',
    'React',
    'Vue, js',
    'Angular',
    'Svelte',
    'C'],
['¿Qué operador se usa para "spread" en JavaScript?',
    '...',
    ' ->',
    '=>',
    '...=',
    'A'],
['¿Qué método de Array en JavaScript modifica el array original?',
    'map()',
    'filter()',
    'splice()',
    'concat()',
    'C'],
['¿Cuál de los siguientes NO es un tipo de dato en JavaScript?',
    'symbol',
    'float',
    'boolean',
    'object',
    'B'],
['¿Qué es un hook en React?',
    'Una función especial para manejar estados o ciclos de vida',
    'Una herramienta de CSS',
    'Un método para llamar a APIs',
    'Una biblioteca para pruebas',
    'A'],
['¿Cuál es el ciclo de vida correcto en componentes de clase en React?',
    'componentDidMount -> componentDidUpdate -> componentWillUnmount',
    'componentWillUnmount -> componentDidMount -> componentDidUpdate',
    'componentDidUpdate -> componentDidMount -> componentWillUnmount',
    'componentDidMount -> componentWillUnmount -> componentDidUpdate',
    'A']]